    <!-- General Conditions -->
    <div class="control-group">
      <div class="general-conditions-wrapper">
        <?php if (ICL_LANGUAGE_CODE=='ca'){ ?>
        <h3>CONDICIONS GENERALS</h3>
        <h4>RELACIÓ ENTRE GUANYEM BARCELONA I EL COL·LABORADOR</h4>

        <p>LA REALITZACIÓ D’APORTACIONS ECONÒMIQUES NO IMPLICA LA VINCULACIÓ DEL COL·LABORADOR AMB GUANYEM BARCELONA NI LI CONFEREIX LA CONDICIÓ LEGAL DE SOCI, AFILIAT O SIMPATITZANT, NI LI ATORGA DRETS DAVANT L'ASSOCIACIÓ NI EL PARTIT, LA INSCRIPCIÓ DEL QUAL ESTÀ PENDENT D'APROVACIÓ, NI QUEDA OBLIGAT PELS SEUS ESTATUTS I RESTA DE NORMES INTERNES. D’ACORD AMB EL QUE S'ESTABLEIX LA LLEI 4/2008, DEL 24 D'ABRIL, DEL LLIBRE TERCER DEL CODI CIVIL DE CATALUNYA, RELATIU A LES PERSONES JURÍDIQUES; LA LLEI ORGÀNICA 1/2002, DEL 22 DE MARÇ, REGULADORA DEL DRET D'ASSOCIACIÓ; LA LLEI ORGÀNICA 8/2007, DE 4 DE JULIOL, DE FINANCIACIÓ DE PARTITS POLÍTICS, EL VOSTRE DONATIU TINDRÀ LA CONSIDERACIÓ D’“APORTACIÓ PRIVADA”, DIFERENT DE LES QUOTES DE SOCIS, AFILIATS O SIMPATITZANTS.</p>

        <h4>PROTECCIÓ DE DADES DE CARÀCTER PERSONAL</h4>

        <p>GUANYEM BARCELONA , D’ACORD AMB LA LLEI ORGÀNICA 15/1999, DE PROTECCIÓ DE DADES DE CARÀCTER PERSONAL, US INFORMA QUE LES VOSTRES DADES SERAN INCORPORADES AL FITXER “APORTACIONS”, DEL QUAL ÉS RESPONSABLE GUANYEM BARCELONA, QUE LES EMPRARÀ PER TRAMITAR LA VOSTRA COL·LABORACIÓ, GESTIONAR ELS CÀRRECS BANCARIS I COMPLIR AMB LA NORMATIVA DE FINANÇAMENT D'ASSOCIACIONS I DE PARTITS POLÍTICS, AIXÍ COM AMB FINALITATS ESTADÍSTIQUES I FER-VOS ARRIBAR PERIÒDICAMENT INFORMACIÓ DE LES SEVES ACTIVITATS. VOS CONCEDIU EL CONSENTIMENT EXPRÉS PERQUÈ AQUESTES DADES PASSIN A FORMAR PART DE GUANYEM BARCELONA, TANT DE L'ASSOCIACIÓ COM DEL PARTIT POLÍTIC, LA INSCRIPCIÓ DEL QUAL ESTÀ PENDENT D'APROVACIÓ. <span class="stripe-legal">GUANYEM BARCELONA LI INFORMA QUE LES SEVES DADES TAMBÉ SERAN TRANSFERIDES I EMMAGATZEMADES PER STRIPE, Inc. NOMÉS AMB LA FINALITAT DE PROCEDIR A L'ACTUAL TRANSACCIÓ DINERÀRIA. SE LI INFORMA QUE STRIPE, Inc. POTSER EMMAGATZEMI I PROCESSI LES SEVES DADES FORA DEL TERRITORI DE LA UE, SEMPRE D'ACORD AMB LA SEVA CERTIFICACIÓ SAFE HARBOR/PORT SEGUR ACREDITADA PEL <a href="http://export.gov/safeharbor/" rel="external">U.S. DEPARTMENT OF COMMERCE</a></span>. PER EXERCIR ELS VOSTRES DRETS D’ACCÉS, RECTIFICACIÓ, CANCEL·LACIÓ O OPOSICIÓ, COM ARA CANCEL·LAR LA SUBSCRIPCIÓ, MODIFICAR LES DADES BANCÀRIES O L’IMPORT I FREQÜÈNCIA DE LA VOSTRA APORTACIÓ, PODEU ENVIAR UN CORREU ELECTRÒNIC A TRESORERIA@GUANYEMBARCELONA.CAT, INDICANT LA REFERÈNCIA “MODIFICACIÓ DE L’APORTACIÓ” O, PER CORREU POSTAL A LA SEU SOCIAL SÍTIA AL CARRER CASTILLEJOS, 233, BAIXOS, DE BARCELONA, ADJUNTANT CÒPIA DEL VOSTRE DOCUMENT NACIONAL D’IDENTITAT.</p>

        <h4>CONSENTIMENT DE L'ORDRE DE DOMICILIACIÓ I CÀRRECS EN TARGETA DE CRÈDIT O DÈBIT</h4>

        <p>EN PRÉMER EL BOTÓ “ENVIA” VOS AUTORITZEU A GUANYEM BARCELONA I A LA VOSTRA ENTITAT BANCÀRIA A EFECTUAR LES OPERACIONS DE COBRAMENT MITJANÇANT CÀRRECS AL COMPTE BANCARI O A LA TARGETA FINANCERA QUE ENS HEU FACILITAT, PER L’IMPORT I AMB LA FREQÜÈNCIA QUE ENS HEU INDICAT AL FORMULARI. ELS CÀRRECS DOMICILIATS I ELS CÀRRECS A LA TARGETA FINANCERA ES REALITZARAN ENTRE ELS DIES 1 I 15 DE CADA MES, TRIMESTRE O ANY EN FUNCIÓ DE LA FREQÜÈNCIA DE PAGAMENT QUE HEU SELECCIONAT.</p>
        <?php }elseif(ICL_LANGUAGE_CODE=='es'){ ?>
        <h3>CONDICIONES GENERALES</h3>
        <h4>RELACIÓN ENTRE GUANYEM BARCELONA Y EL COLABORADOR.</h4>

        <p>LA REALIZACIÓN DE APORTACIONES ECONÓMICAS NO IMPLICA LA VINCULACIÓN DEL COLABORADOR CON GUANYEM BARCELONA NI LE CONFIERE LA CONDICIÓN LEGAL DE SOCIO, AFILIADO O SIMPATIZANTE, NI DE DERECHOS FRENTE A LA ASOCIACIÓN NI AL PARTIDO CUYA INSCRIPCIÓN SE ENCUENTRA PENDIENTE DE APROBACIÓN, NI QUEDA OBLIGADO POR SUS ESTATUTOS Y DEMÁS NORMAS INTERNAS. CONFORME A LO DISPUESTO EN LA LEY 4/2008, DE 24 DE ABRIL, DEL LIBRO TERCERO DEL CÓDIGO CIVIL DE CATALUÑA, RELATIVO A LAS PERSONAS JURÍDICAS; LA LEY ORGÁNICA 1/2002, DE 22 DE MARZO, REGULADORA DEL DERECHO DE  ASOCIACIÓN,  LA LEY ORGÁNICA 8/2007, DE 4 DE JULIO, DE FINANCIACIÓN DE PARTIDOS POLÍTICOS SU DONATIVO TENDRÁ LA CONSIDERACIÓN DE “APORTACIÓN PRIVADA”, DISTINTA DE LAS CUOTAS DE SOCIOS, AFILIADOS O SIMPATIZANTES.</p>

        <h4>PROTECCIÓN DE DATOS DE CARÁCTER PERSONAL.</h4>

        <p>GUANYEM BARCELONA, DE ACUERDO CON LA LEY ORGÁNICA 15/1999 DE PROTECCIÓN DE DATOS DE CARÁCTER PERSONAL, LE INFORMA DE QUE SUS DATOS SERÁN INCORPORADOS AL FICHERO “APORTACIONES”, DEL QUE ES RESPONSABLE GUANYEM BARCELONA, QUE LOS UTILIZARÁ PARA TRAMITAR SU COLABORACIÓN, GESTIONAR LOS ADEUDOS BANCARIOS, CUMPLIR CON LA NORMATIVA DE FINANCIACIÓN DE ASOCIACIONES Y PARTIDOS POLÍTICOS, PARA FINES ESTADÍSTICOS Y HACERLE LLEGAR PERIÓDICAMENTE INFORMACIÓN SOBRE SUS ACTIVIDADES. USTED CONCEDE SU CONSENTIMIENTO EXPRESO PARA QUE DICHOS DATOS PASEN A FORMAR PARTE DE GUANYEM BARCELONA, TANTO EN LA ASOCIACIÓN COMO EN EL PARTIDO POLÍTICO  CUYA INSCRIPCIÓN SE ENCUENTRA PENDIENTE DE APROBACIÓN. <span class="stripe-legal">GUANYEM BARCELONA LE INFORMA QUE SUS DATOS TAMBIÉN SERÁN TRANSFERIDOS Y ALMACENADOS POR STRIPE, Inc. CON EL SÓLO FIN DE PROCEDER A ESTA TRANSACCIÓN DINERARIA. SE LE INFORMA QUE STRIPE, Inc. PUEDE QUE ALMACENE Y PROCESE SUS DATOS FUERA DEL TERRITORIO UE, SIEMPRE DE ACUERDO A SU CERTIFICADO SAFE HARBOR/PUERTO SEGURO EMITIDO POR EL <a href="http://export.gov/safeharbor/" rel="external">U.S. DEPARTMENT OF COMMERCE</a></span>. PARA EJERCER SUS DERECHOS DE ACCESO, RECTIFICACIÓN, CANCELACIÓN U OPOSICIÓN, COMO CANCELAR SU SUSCRIPCIÓN, MODIFICAR LOS DATOS BANCARIOS O EL IMPORTE Y FRECUENCIA DE SU APORTACIÓN, PUEDE MANDAR UN CORREO ELECTRÓNICO A TRESORERIA@GUANYEMBARCELONA.CAT INDICANDO LA REFERENCIA “MODIFICACIÓN DE LA APORTACIÓN” O, POR CORREO POSTAL EN LA SEDE SOCIAL SITA EN LA CALLE CASTILLEJOS, 233, BAJOS, DE BARCELONA, ADJUNTANDO COPIA DE SU DOCUMENTO NACIONAL DE IDENTIDAD.</p>

        <h4>CONSENTIMIENTO ORDEN DE DOMICILIACIÓN  Y CARGOS EN TARJETA DE CRÉDITO O DÉBITO.</h4>

        <p>AL PULSAR EL BOTÓN “ENVÍA” USTED AUTORIZA A GUANYEM BARCELONA Y A SU ENTIDAD BANCARIA A EFECTUAR LAS OPERACIONES DE COBRO MEDIANTE ADEUDOS Y CARGOS EN LA CUENTA BANCARIA O EN LA TARJETA FINANCIERA QUE USTED NOS HA FACILITADO, POR EL IMPORTE Y CON LA FRECUENCIA QUE NOS HA INDICADO EN EL FORMULARIO. LOS ADEUDOS DOMICILIADOS Y LOS CARGOS EN TARJETA SE REALIZARÁN ENTRE EL DÍA 1 Y 15 DE CADA MES, TRIMESTRE O AÑO DEPENDIENDO DE LA FRECUENCIA DE PAGO QUE HA ELEGIDO.</p>
        <?php } ?>
      </div>
    </div>
    <!-- Accept conditions -->
    <div class="control-group">
      <label class="checkbox">
        <input type="checkbox" name="fullstripe_accept_terms" id="fullstripe_accept_terms" value="1">
        <?php _e("Agree to General Terms", "wp-full-stripe"); ?>
      </label>
    </div>